name: Lighthouse Accessibility and UI/UX Scanning

on:
  push:
    branches:
      - main

jobs:
    lhci:
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Use Node.js 21.x
            uses: actions/setup-node@v3
            with:
              node-version: 21.x
          - name: npm install, build
            run: |
              npm install
              npm run build 
          - name: run Lighthouse CI
            run: |
              npm install -g @lhci/cli@0.14.x
              lhci autorun
            env:
              LHCI_GITHUB_TOKEN: ${{ secrets.LH_GITHUB_TOKEN }}
